version: "3.8"

services:
  dynamodb-local:
    image: amazon/dynamodb-local:1.16.0
    container_name: app-dynamodb
    hostname: app-dynamodb
    volumes:
      - app_dynamodb:/home/dynamodblocal
    working_dir: /home/dynamodblocal
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
    restart: unless-stopped

  dynamodb_admin:
    image: aaronshaf/dynamodb-admin
    container_name: app-dynamodb_admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://app-dynamodb:8000
    depends_on:
      - dynamodb-local
    restart: unless-stopped

volumes:
  app_dynamodb:
    driver: local
